blog/urls.py
from django.urls import path

from blog import views as blog_views
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostList.as_view(), name='index'),
    path('category/<int:category>', CategoryList.as_view(), name='category'),
    path('search/', Search.as_view(), name='search'),
    path('article/<int:pk>/', PostView.as_view(), name='article'),
    path('article/<int:article_id>/comment/', blog_views.post_comment, name='comment'),
    path('about/', blog_views.about, name='about'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from blog.views import error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', RedirectView.as_view(url='/blog/')),  # redirect '/' to '/blog/' as we only have one app yet.
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('404/', error, name='error'),
]

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, unique=True, db_index=True)

    def get_absolute_url(self):
        pass

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100, unique=True)
    content = RichTextField(config_name='mycfg')
    posted_time = models.DateField('date posted', auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=1)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Comments(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nickname', max_length=20)
    email = models.EmailField()
    content = models.TextField()
    posted_time = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Post, on_delete=models.CASCADE)
    reply = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return self.content

blog/forms.py
from django import forms

from .models import Comments


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'email', 'content']
        widgets = {
            'name': forms.TextInput(attrs={'id': 'name', 'class': "form-control", 'placeholder': 'Name*'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'class': "form-control", 'placeholder': 'Email*'}),
            'content': forms.Textarea(
                attrs={'id': 'content', 'class': "form-control", 'placeholder': 'Messages...', 'cols': 45, 'rows': 4})
        }


class SignInForm(forms.ModelForm):
    pass

blog/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, ListView

from blog.models import Category, Comments, Post, Tag
from .forms import CommentForm


# Create your views here.
class PostList(ListView):
	"""
	list view for index.html
	"""
	template_name = 'blog/index.html'
	queryset = Post.objects.all().order_by('-id')
	paginate_by = 5  # set numbers of posts per page.


class CategoryList(ListView):
	"""
	list all posts in a given category ordered by posted time.
	"""
	template_name = 'blog/category.html'
	paginate_by = 5

	def get_queryset(self):  # get queryset
		self.category = get_object_or_404(Category, id=self.kwargs['category'])
		return Post.objects.filter(category=self.category).order_by('-id')

	def get_context_data(self, **kwargs):  # pass extra arguments to template.
		context = super().get_context_data(**kwargs)
		context['category'] = self.category  # the variable name "category" will be used in template in {{category}}.
		return context


class PostView(DetailView):
	"""
	display an article's detail.
	"""
	model = Post
	template_name = 'blog/article.html'

	# inheritance Class DetailView and extend to define new attributes
	def __init__(self):
		self.comment_list = []  # the final list of comments
		self.top_level = []  # save top comments in a list
		self.sub_level = {}
		super().__init__()

	# define comment function
	def comment_sort(self, comments):
		"""
		sort comments in a parent-kid recursive structure.
		:param comments: all comments belong to an article
		:return: sorted comment list of an article

		"""
		# use list generate expression to place instead of codes in block quotes above.
		[self.top_level.append(comment) for comment in comments if comment.reply is None]
		[self.sub_level.setdefault(comment.reply.id, []).append(comment) for comment in comments if
		 comment.reply is not None]
		[self.format_show(top_comment) for top_comment in self.top_level]  # call a recursive function
		return self.comment_list  # return sorted list of comments.

	def format_show(self, comment):
		"""
		:param comment: a parent comment
		:return: the list of parent comment and its kid comments
		"""
		self.comment_list.append(comment)
		try:
			kids = self.sub_level[comment.id]  # obtain all replay belongs to a comment.
		except KeyError:  # if no replay
			return self.comment_list  # end recursive
		else:
			[self.format_show(kid) for kid in kids]  # next recursive

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		# get session and save into context.
		try:
			context['session'] = {
				'name': self.request.session['name'],
				'email': self.request.session['email'],
				'content': self.request.session['content']
			}
		except Exception:  # do nothing if has exception
			pass

		# list comments
		comments = get_list_or_404(Comments, article=self.kwargs['pk'])  # query comments by post id.
		context['comment_list'] = self.comment_sort(comments)

		# pass comment form to template
		comment_form = CommentForm()
		context['comment_form'] = comment_form

		return context


class Search(ListView):
	model = Post
	template_name = 'blog/search.html'
	paginate_by = 5

	def get_queryset(self):
		result = super(Search, self).get_queryset()
		queries = self.request.GET.get('key')
		if queries:
			result = Post.objects.filter(Q(title__icontains=queries) | Q(content__icontains=queries)).order_by('-id')
		return result

	def get_context_data(self, **kwargs):
		context = super(Search, self).get_context_data(**kwargs)
		context['tags'] = Tag.objects.all()
		context['categories'] = Category.objects.all()
		context['key'] = self.request.GET.get('key')
		return context


def about(request):
	return render(request, 'blog/about.html')


def error(request):
	return render(request, 'blog/404.html')


@require_POST  # only accept a POST request; otherwise return a  django.http.HttpResponseNotAllowed
def post_comment(request, article_id):
	"""
	function to handle post request from comment form.
	if valid form, save form data into database and return a redirected page.
	if not, return previous page.
	:param article_id: captured from url.
	:param request: http POST request
	:return: redirected page if valid; otherwise, previous page with prompt message
	"""
	# session input to auto-fill
	request.session['name'] = request.POST.get('name')
	request.session['email'] = request.POST.get('email')
	comment = Comments()  # create a instance of Comments class
	comment.article = get_object_or_404(Post, pk=article_id)
	if request.POST.get('reply') != '0':  # if reply to a comment
		comment.reply = Comments.objects.get(pk=request.POST.get('reply'))  # get reply objective
	form = CommentForm(request.POST, instance=comment)
	# combine input form data and the instance to create a whole CommentForm instance
	if form.is_valid():  # if form is not valid
		try:
			messages.success(request, 'Your comment was added successfully!')
			form.save()  # save posted form date into database
			request.session['content'] = ''  # session nothing if successful
			return redirect('blog:article', article_id)
		except Exception:
			request.session['content'] = request.POST.get('content')  # save input content in session if fail
			messages.warning(request, 'AN EXCEPTION OCCURS!')
	messages.error(request, 'Please correct your error above!')  # if not a valid form


class NavList(ListView):  # list category names in navigation bar
	model = Category
	template_name = 'blog/nav.html'

blog/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block main_content %}
    <h1>About information </h1>
    <p>This is a blog which is written by myself originally for improving my programming skills! I may put some useful
        or interesting articles, videos and music on this site. Emmm.... Maybe!</p>
    <p>Here is a view of my project, which is the layout I designed at the beginning! </p>
    <iframe src="http://www.xmind.net/embed/hppW" width="100%" height="540px" frameborder="0" scrolling="no"></iframe>
{% endblock %}

blog/templates/article.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block main_content %}
    <!-- post block -->
    <div class="blog-post">
        <h3 class="blog-post-title"><a>{{ object.title|title }}</a></h3>
        <p class="blog-post-meta">{{ object.posted_time }} by <a href="#">{{ object.author }}</a></p>
        <hr>
        <p>{{ object.content|safe }}</p>
    </div>
    <hr>
    <div class="blog-category">
        {% url 'blog:category' object.category.id as category_id %}
        <p>Categories: <a href="{{ category_id }}">{{ object.category }}</a>
        </p>
    </div>
    <div class="blog-tag">
        <p>Tags:
            {% for tag in post.tag.all %}
                <a href="#">{{ tag }}</a>
                {% if not forloop.last %}
                    |
                {% endif %}
            {% endfor %}
        </p>
    </div>
    <hr style="margin-bottom: 3rem">
    <!-- comments block --> {# or use line comment #}
    {% comment %}
    or a block commnet tag.
    {% endcomment %}
    <div class="blog-comments">
        <h2 id="publish">Comments</h2>
        <hr>
        <!-- a comment form created by ModelFrom module -->
        <div id="respond" class="comment-respond">
            <h3>Leave a message</h3>
            <form action="{% url 'blog:comment' %}" method="post" id="commentform" class="comment-form">
                <!-- hidden element, used to record replied user. -->
                <p class="comment-notes"><span id="email-notes">Your email address will not be published.</span>
                    Required fields are marked <span class="required">*</span></p>
                {% csrf_token %}
                <div class="form-group comment-form-author">{{ comment_form.name }}</div>
                <div class="form-group comment-form-email">{{ comment_form.email }}</div>
                <div class="form-group comment-form-comment">{{ comment_form.content }}</div>
                <div class="form-group comment-form-comment">
                    <input type="hidden" id="article" name="article" value="{{ object.id }}">
                </div>
                <div class="form-group comment-form-comment">
                    <input type="hidden" id="reply" name="reply" value="0">
                </div>
                <p class="form-submit">
                    <input name="submit" type="submit" id="submit_comment" class="submit" value="Post Comment">
                </p>

                <!-- message flash block-->
                {% include 'messages.html' %}
            </form>
        </div>
        <hr>
        {% for comment in comment_list %}
            {% if comment.reply == None %}  <!-- if no replay, then its a parent comment -->
                <div class="parent-comment">
                    <p class="comment-nav">{{ comment.name }} ({{ comment.posted_time }})</p>
                    <div class="comment-content" style="position: relative;">{{ comment.content }}
                        <a href="#publish" style="position: absolute; right: 0;bottom: 0;"
                           onclick="reply('{{ comment.name }}',{{ comment.id }})">reply</a>
                    </div>
                </div>
            {% else %}
                <div class="children-comment">
                    <p class="comment-nav">{{ comment.name }} >>> {{ comment.reply.name }}
                        ({{ comment.posted_time }})</p>
                    <div class="comment-content" style="position: relative;">{{ comment.content }}
                        <a href="#publish" style="position: absolute; right: 0;bottom: 0;"
                           onclick="reply('{{ comment.name }}',{{ comment.id }})">reply</a>
                    </div>
                </div>
            {% endif %}
        {% empty %}
            <a>No comments yet!</a>
        {% endfor %}
    </div>
    <script>
        function reply(comment_name, comment_id) {
            $('#content').attr('placeholder', 'Reply to ' + comment_name + ':'); // 设置内容输入框的提示
            $('#reply').val(comment_id) //设置隐藏元素的值为评论目标的id
        }

        function onload() {     // put this function in body element to load session
            $('#name').val('{{ session.name }}'); // 设置昵称为session中的昵称
            $('#email').val('{{ session.email }}'); // 设置邮箱为session中的邮箱
            $('#content').val('{{ session.content }}') // 设置内容为session中的内容
        }
    </script>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <!-- Custom CSS  -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
    <!-- block title -->
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body onload="onload()">
<!-- navigation block -->
{% include 'nav.html' %}
<!-- main block -->
<main role="main" class="container">
    <div class="row" style="padding-top: 40px">
        <div class="col-md-8 blog-main">
            {% block main_content %}This is main content!{% endblock %}
        </div>
        {% include 'sidebar.html' %}
    </div>
    <hr class="featurette-divider">
    <!-- footer block -->
    {% include 'bottom.html' %}
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<script src="{% static '/ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static '/ckeditor/ckeditor-init.js' %}"></script>
</body>
</html>

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}About{% endblock %}

{% block main_content %}
    <h1>About information </h1>
    <p>This is a blog which is written by myself originally for improving my programming skills! I may put some useful
        or interesting articles, videos and music on this site. Emmm.... Maybe!</p>
    <p>Here is a view of my project, which is the layout I designed at the beginning! </p>
    <p>Here is a beautiful view! Enjoy it!</p>
    {% load static %}
    <img class="" src="{% static 'blog/images/background copy.gif' %}" style="width: 100%; height: auto">
{% endblock %}

blog/templates/blog/article.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block main_content %}
    <!-- post block -->
    <div class="blog-post">
        <h3 class="blog-post-title"><a>{{ object.title|title }}</a></h3>
        <p class="blog-post-meta">{{ object.posted_time }} by <a href="#">{{ object.author }}</a></p>
        <hr>
        <p>{{ object.content|safe }}</p>
    </div>
    <hr>
    <div class="blog-category">
        {% url 'blog:category' object.category.id as category_id %}
        <p>Categories: <a href="{{ category_id }}">{{ object.category }}</a>
        </p>
    </div>
    <div class="blog-tag">
        <p>Tags:
            {% for tag in post.tag.all %}
                <a href="#">{{ tag }}</a>
                {% if not forloop.last %}
                    |
                {% endif %}
            {% endfor %}
        </p>
    </div>
    <hr style="margin-bottom: 3rem">
    <!-- comments block --> {# or use line comment #}
    {% comment %}
    or a block commnet tag.
    {% endcomment %}
    {% include 'blog/comments.html' %}
    <script>
        function reply(comment_name, comment_id) {
            $('#content').attr('placeholder', 'Reply to ' + comment_name + ':');
            $('#reply').val(comment_id)
        }

        function onload() {     // put this function in body element to load session
            $('#name').val('{{ session.name }}');
            $('#email').val('{{ session.email }}');
            $('#content').val('{{ session.content }}')
        }
    </script>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <!-- Custom CSS  -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/blog.css' %}">
    <!-- block title -->
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body onload="onload()">
<!-- navigation block -->
{% include 'blog/nav.html' %}
<!-- main block -->
<main role="main" class="container">
    <div class="row" style="padding-top: 40px">
        <div class="col-md-8 blog-main">
            {% block main_content %}This is main content!{% endblock %}
        </div>
        {% include 'blog/sidebar.html' %}
    </div>
    <hr class="featurette-divider">
    <!-- footer block -->
    {% include 'blog/bottom.html' %}
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<script src="{% static '/ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static '/ckeditor/ckeditor-init.js' %}"></script>
</body>
</html>

blog/templates/blog/bottom.html
<footer class="container">
    <div class="row">
        <div class="col-md-8">
            <p>© 2017-2018 · CJJ's Blog · Based on Django · All Rights Reserved</p>
            <p><a href="#">Privacy</a> · <a href="#">Terms</a>
            </p>
        </div>
        <div class="col-md-4">
            <p class="float-left"><a href="#">Back to top</a></p>
        </div>
    </div>
</footer>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block title %}Category - {{ category }}{% endblock %}
{% block main_content %}
    <h3 class="pb-3 mb-4 font-italic border-bottom">Category - {{ category }}</h3>
    {% for post in page_obj.object_list %}
        {% include 'blog/post_list_body.html' %}
    {% empty %}
        <h3>No posts about {{ category }}!</h3>
    {% endfor %}
    {% include 'blog/paginator.html' %}
{% endblock %}

blog/templates/blog/comments.html
<div class="blog-comments">
    <h2 id="publish">Comments</h2>
    <hr>
    <!-- a comment form created by ModelFrom module -->
    <div id="respond" class="comment-respond">
        <h3>Leave a message</h3>
        <form action="{% url 'blog:comment' post.id %}" method="post" id="commentform" class="comment-form">
            <!-- hidden element, used to record replied user. -->
            <p class="comment-notes"><span id="email-notes">Your email address will not be published.</span>
                Required fields are marked <span class="required">*</span></p>
            {% csrf_token %}
            <div class="form-group comment-form-author">{{ comment_form.name }}</div>
            <div class="form-group comment-form-email">{{ comment_form.email }}</div>
            <div class="form-group comment-form-comment">{{ comment_form.content }}</div>
            <div class="form-group comment-form-comment">
                <input type="hidden" id="reply" name="reply" value="0">
            </div>
            <p class="form-submit">
                <input name="submit" type="submit" id="submit_comment" class="submit" value="Post Comment">
            </p>

            <!-- message flash block-->
            {% include 'blog/messages.html' %}
        </form>
    </div>
    <hr>
    {% for comment in comment_list %}
        {% if comment.reply is None %}  <!-- if no replay, then its a parent comment -->
            <div class="parent-comment">
                <p class="comment-nav">{{ comment.name }} ({{ comment.posted_time }})</p>
                <div class="comment-content" style="position: relative;">{{ comment.content }}
                    <a href="#publish" style="position: absolute; right: 0;bottom: 0;"
                       onclick="reply('{{ comment.name }}',{{ comment.id }})">reply</a>
                </div>
            </div>
        {% else %}
            <div class="children-comment">
                <p class="comment-nav">{{ comment.name }} >>> {{ comment.reply.name }}
                    ({{ comment.posted_time }})</p>
                <div class="comment-content" style="position: relative;">{{ comment.content }}
                    <a href="#publish" style="position: absolute; right: 0;bottom: 0;"
                       onclick="reply('{{ comment.name }}',{{ comment.id }})">reply</a>
                </div>
            </div>
        {% endif %}
    {% empty %}
        <a>No comments yet!</a>
    {% endfor %}
</div>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Home{% endblock %}
{% block main_content %}
    <h3 class="pb-3 mb-4 font-italic border-bottom">Recent Post</h3>
    {% for post in page_obj.object_list %}
        {% include 'blog/post_list_body.html' %}
    {% empty %}
        <h3> No posts yet!</h3>
    {% endfor %}
    {% include 'blog/paginator.html' %}
{% endblock %}

blog/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


</body>
</html>

blog/templates/blog/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="{{ message.tag }}" id="comment_message"
             style="margin-top: 10px;vertical-align: middle;color: green">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

blog/templates/blog/nav.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'blog:index' %}">My Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:category' 2 %}">Python</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:category' 3 %}">R</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:category' 4 %}">Html</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:category' 1 %}">Others</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Documents</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'error' %}">404</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0" method="get" action="{% url 'blog:search' %}">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="key"
                       value="{{ key }}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Go!</button>
            </form>
            <form class="form-inline mt-2 mt-md-0" method="get" action="/admin" style="margin-left: 4px">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
            </form>
        </div>
    </nav>
</header>

blog/templates/blog/paginator.html
<nav class="blog-pagination" style="position: absolute;bottom: 0;">
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-primary" href="/?page={{ page_obj.previous_page_number }}">&laquo;</a>
    {% else %}
        <a class="btn btn-outline-primary disabled">&laquo;</a>
    {% endif %}
    {% for page_number in paginator.page_range %}
        {% if page_number != page_obj.number %}
            <a class="btn btn-outline-secondary " href="/?page={{ page_number }} }}">{{ page_number }}</a>
        {% else %}
            <a class="btn btn-outline-secondary active">{{ page_number }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-primary" href="/?page={{ page_obj.next_page_number }}">&raquo;</a>
    {% else %}
        <a class="btn btn-outline-primary disabled">&raquo;</a>
    {% endif %}
</nav>

blog/templates/blog/post_list_body.html
<div class="blog-post">
    {% url 'blog:article' post.id as post_id %}
    <h3 class="blog-post-title"><a href="{{ post_id }}">{{ post.title|title }}</a></h3>
    <p class="blog-post-meta">{{ post.posted_time }} by <a href="#">{{ post.author }}</a></p>
    <p>{{ post.content|truncatechars_html:200|striptags }}</p>
    <a class="btn" href="{{ post_id }}">Read >></a>
</div>
<hr class="featurette-divider">

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% block title %}Search{% endblock %}
{% block main_content %}
    {% if key %}
        <h3 class="pb-3 mb-4 font-italic border-bottom">Search for "{{ key }}":</h3>
        {% for post in page_obj.object_list %}
            {% include 'blog/post_list_body.html' %}
        {% empty %}
            <h3>No post about "{{ key }}" !</h3>
        {% endfor %}
        {% include 'blog/paginator.html' %}
    {% else %}
        <h3>Do you search for:</h3>
        <hr>
        <div class="blog-category">
            <p>Categories:
                {% for category in categories %}
                    <a href="{% url 'blog:category' category.id %}">{{ category }}</a>
                {% empty %}
                    <a>No categories yet!</a>
                {% endfor %}</p>
        </div>
        <div class="blog-tag">
            <p>Tags:
                {% for tag in tags %}
                    <a href="#">{{ tag }}</a>
                    {% if not forloop.last %}
                        |
                    {% endif %}
                {% empty %}
                    <a>No tags yet!</a>
                {% endfor %}
            </p>
        </div>
        {% load static %}
        <img class="" src="{% static 'blog/images/background copy.gif' %}" style="width: 100%; height: auto">
    {% endif %}
{% endblock %}